name: "pack-repo"
version: "0.1.0"
usage: "The Scaffold pack repository plugin"
description: "The Scaffold pack repository plugin"
command: "$SCAFFOLD_PLUGIN_DIR/bin/pack-repo"

hooks:
  install: "cd $SCAFFOLD_PLUGIN_DIR && chmod +x ./scripts/get.sh && ./scripts/get.sh"
  update: "cd $SCAFFOLD_PLUGIN_DIR && chmod +x ./scripts/get.sh && ./scripts/get.sh"
