name: "pack-repo"
version: "0.4.3"
usage: "The Scaffold pack repository plugin"
description: "The Scaffold pack repository plugin"
command: "$SCAFFOLD_PLUGIN_DIR/bin/pack-repo"
#hooks:
#  bash:
#    install: "$SCAFFOLD_PLUGIN_DIR/scripts/get.sh"
#  powershell:
#    install: >
#      powershell.exe "&'$env:SCAFFOLD_PLUGIN_DIR\scripts\get.ps1'"